const pool = require('./db');

const dropTablesText = `
  DROP TABLE IF EXISTS "transactions" CASCADE;
  DROP TABLE IF EXISTS "maintenance_logs" CASCADE;
  DROP TABLE IF EXISTS "projects" CASCADE;
  DROP TABLE IF EXISTS "contractors" CASCADE;
  DROP TABLE IF EXISTS "inventory" CASCADE;
  -- Also dropping the generic ones we might have made by mistake earlier
  DROP TABLE IF EXISTS "users" CASCADE;
  DROP TABLE IF EXISTS "categories" CASCADE;
`;

const createTablesText = `
  -- 1. Inventory Table
  CREATE TABLE "inventory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "category" varchar NOT NULL,
    "quantity" integer DEFAULT 0,
    "location" varchar,
    "status" varchar DEFAULT 'AVAILABLE',
    "unit_cost" decimal
  );

  -- 2. Contractors Table
  CREATE TABLE "contractors" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" varchar NOT NULL,
    "last_name" varchar,
    "contact_info" varchar
  );

  -- 3. Projects Table
  CREATE TABLE "projects" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "address" varchar,
    "status" varchar DEFAULT 'ACTIVE',
    "start_date" date
  );

  -- 4. Maintenance Logs Table
  CREATE TABLE "maintenance_logs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "inventory_id" integer REFERENCES "inventory" ("id"),
    "description" varchar NOT NULL,
    "service_date" date DEFAULT (now()),
    "cost" decimal
  );

  -- 5. Transactions Table
  CREATE TABLE "transactions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "inventory_id" integer REFERENCES "inventory" ("id"),
    "contractor_id" integer REFERENCES "contractors" ("id"),
    "project_id" integer REFERENCES "projects" ("id"),
    "action_type" varchar NOT NULL,
    "quantity_changed" integer NOT NULL,
    "transaction_date" timestamp DEFAULT (now())
  );
`;

const resetDatabase = async () => {
    try {
        console.log('🗑️  Dropping old tables...');
        await pool.query(dropTablesText);
        console.log('✅ Old tables dropped.');

        console.log('🏗️  Building SupplySync tables...');
        await pool.query(createTablesText);
        console.log('✅ New tables created successfully!');

    } catch (err) {
        console.error('❌ Error resetting database:', err);
    } finally {
        pool.end();
    }
};

resetDatabase();